GET http://localhost:3001/api/user/Madeline HTTP/1.1
content-type: application/json

{
    "username": "Madeline"
}

###
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
    "username": "PolkaDotMask",
    "password": "Password_1"
}

###
POST http://localhost:3001/api/user/logout HTTP/1.1

###
GET http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{
    "username": "Unique3",
    "password": "Password_1",
    "email": "unique3@gmail.com"
}