POST http://localhost:3001/api/post/Christian HTTP/1.1
content-type: application/json

{
    "username": "Christian",
    "profilePicture": "../img/NoImageFound.png",
    "postTitle": "uivyyvyyvvv title",
    "postID": "5e9e4c109c1acd1b80368c67",
    "commentBody": " is my qwerqwerqwerqwer",
    "postBody": "eeee eeeee the newly created post",
    "categories": ["Food", "Family"]
}

###
POST http://localhost:3001/api/user/signup HTTP/1.1
Content-Type: application/json

{
    "username": "hi",
    "password": "123456",
    "email": "mint2@mail.com"
}

###
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
    "username": "Seohui",
    "password": "Password_1"
}

###
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
    "username": "PolkaDotMask",
    "password": "Password_1"
}

###
POST http://localhost:3001/api/user/logout HTTP/1.1


###
GET http://localhost:3001/api/user/profile HTTP/1.1
Content-Type: application/json

{
    "username": "hello"
}
###
GET http://localhost:3001/api/user HTTP/1.1
content-type: application/json

{
    "username": "Unique3",
    "password": "Password_1",
    "email": "unique3@gmail.com"
}
