GET http://localhost:3001/api/post HTTP/1.1
content-type: application/json

{
    "username": "My guy",
    "password": "TestPW",
    "email": "email@gmail.com"
}

###
POST http://localhost:3001/api/user/login HTTP/1.1
content-type: application/json

{
    "username": "My guy",
    "password": "TestPW"
}

###
POST http://localhost:3001/api/user/logout HTTP/1.1

